name: Consul Register

on:
   push:
      branches:
         - main
      tags:
         - v*
   pull_request:

concurrency:
   group: merge-${{ github.ref }}

permissions:
   contents: read
   packages: write

jobs:
   build:
      strategy:
         matrix:
            deployable: 
               - image: "consul-register"
                 dockerfile: Dockerfile
               - image: "consul-envoy"
                 dockerfile: Dockerfile.sidecar
      name: "🏗️ Build ${{matrix.deployable.image}}"
      uses: a-ramsay/workflows/.github/workflows/docker-build.yml@main
      with:
         image: ghcr.io/${{ github.repository_owner }}/${{ matrix.deployable.image }}
         dockerfile: ${{ matrix.deployable.dockerfile }}
      secrets: inherit
